language: csharp
branches:  
  only:
    - master
solution: pillowsharp.csproj
mono: none
dotnet: 2.0.0
services:
  - couchdb
before_script: 
  - ./src/dev_couch2_setup.sh
script: 
  - ./src/build.sh
