language: csharp
branches:  
  only:
    - master
solution: pillowsharp.csproj
mono: none
dotnet: 2.0.0
services:
  - couchdb
before_script: #CouchDB2 changed the setup
  -  curl -H "Content-Type: application/json" -X POST -d '{"action":"enable_single_node","username":"admin","password":"admin","bind_address":"0.0.0.0","port":5984,"singlenode":true}' http://localhost:5984/_cluster_setup
script: 
  - ./src/build.sh
branches:  
  only:
    - master
